import { toCanonicalDocumentCode } from '@/features/printing/presentation/canonicalDocumentIdentity'

const a4Items = [
  { description: 'สินค้า / บริการตัวอย่าง A', quantity: '2', unit: 'ชิ้น', price: '2,500.00', amount: '5,000.00' },
  { description: 'สินค้า / บริการตัวอย่าง B', quantity: '1', unit: 'ชุด', price: '5,000.00', amount: '5,000.00' },
]

const taxItems = [
  { description: 'สินค้า / บริการตัวอย่าง', quantity: '1', unit: 'รายการ', price: '10,000.00', amount: '10,000.00' },
]

const baseTotals = [
  ['มูลค่าก่อนภาษี', '10,000.00'],
  ['ภาษีมูลค่าเพิ่ม 7%', '700.00'],
  ['ยอดสุทธิ', '10,700.00'],
]

const DOCUMENT_PREVIEW_FIXTURES = Object.freeze({
  QUOTATION: {
    rendererFamily: 'A4',
    category: 'COMMERCIAL',
    title: 'ใบเสนอราคา',
    englishTitle: 'QUOTATION',
    documentNo: 'QT-2026-0001',
    counterpartyLabel: 'ลูกค้า',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่', '19 สิงหาคม 2569'], ['ยืนราคาถึง', '18 กันยายน 2569']],
    items: a4Items,
    totals: baseTotals,
    signatures: ['ผู้เสนอราคา', 'ผู้อนุมัติ / ลูกค้า'],
  },
  DELIVERY_NOTE: {
    rendererFamily: 'A4',
    category: 'COMMERCIAL',
    title: 'ใบส่งของ',
    englishTitle: 'DELIVERY NOTE',
    documentNo: 'DN-2026-0001',
    counterpartyLabel: 'ผู้รับสินค้า',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่ส่ง', '19 สิงหาคม 2569'], ['อ้างอิง', 'SO-2026-0001']],
    items: a4Items,
    totals: [['รวมจำนวนรายการ', '3 หน่วย']],
    signatures: ['ผู้รับของ', 'ผู้ส่งของ', 'ผู้ตรวจสอบ'],
  },
  CUSTOMER_RECEIPT: {
    rendererFamily: 'A4',
    category: 'FINANCE',
    title: 'ใบเสร็จรับเงิน',
    englishTitle: 'RECEIPT',
    documentNo: 'RC-2026-0001',
    counterpartyLabel: 'ผู้ชำระเงิน',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่รับเงิน', '19 สิงหาคม 2569'], ['วิธีชำระ', 'โอนเงิน']],
    items: taxItems,
    totals: baseTotals,
    signatures: ['ผู้รับเงิน', 'ผู้ชำระเงิน'],
  },
  CUSTOMER_MONEY_RECEIPT: {
    rendererFamily: 'A4',
    category: 'FINANCE',
    title: 'ใบรับเงิน Customer Money',
    englishTitle: 'CUSTOMER MONEY RECEIPT',
    documentNo: 'CMR-2026-0001',
    counterpartyLabel: 'ผู้ชำระเงิน',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่รับเงิน', '19 สิงหาคม 2569'], ['สถานะ', 'รับเงินจริง']],
    items: [{ description: 'รับชำระเงินจากลูกค้า', quantity: '1', unit: 'รายการ', price: '10,700.00', amount: '10,700.00' }],
    totals: [['ยอดรับเงินจริง', '10,700.00']],
    signatures: ['ผู้รับเงิน', 'ผู้ชำระเงิน'],
  },
  DELIVERY_CREDIT_SETTLEMENT: {
    rendererFamily: 'A4',
    category: 'FINANCE',
    title: 'เอกสารตัดยอดใบส่งของเครดิต',
    englishTitle: 'DELIVERY CREDIT SETTLEMENT',
    documentNo: 'DCS-2026-0001',
    counterpartyLabel: 'ลูกค้า',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่ตัดยอด', '19 สิงหาคม 2569'], ['อ้างอิง', 'DN-2026-0001']],
    items: [{ description: 'ตัดยอดใบส่งของเครดิต', quantity: '1', unit: 'เอกสาร', price: '10,700.00', amount: '10,700.00' }],
    totals: [['ยอดตัดชำระ', '10,700.00']],
    signatures: ['ผู้จัดทำ', 'ผู้รับรอง'],
  },
  REFUND_RECEIPT: {
    rendererFamily: 'A4',
    category: 'FINANCE',
    title: 'ใบรับเงินคืน',
    englishTitle: 'REFUND RECEIPT',
    documentNo: 'RF-2026-0001',
    counterpartyLabel: 'ผู้รับเงินคืน',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่คืนเงิน', '19 สิงหาคม 2569'], ['อ้างอิง', 'SALE-2026-0001']],
    items: [{ description: 'คืนเงินค่าสินค้า / บริการ', quantity: '1', unit: 'รายการ', price: '2,140.00', amount: '2,140.00' }],
    totals: [['ยอดคืนเงิน', '2,140.00']],
    signatures: ['ผู้คืนเงิน', 'ผู้รับเงินคืน'],
  },
  PURCHASE_ORDER: {
    rendererFamily: 'A4',
    category: 'PROCUREMENT',
    title: 'ใบสั่งซื้อ',
    englishTitle: 'PURCHASE ORDER',
    documentNo: 'PO-2026-0001',
    counterpartyLabel: 'ผู้ขาย',
    counterpartyName: 'บริษัท ซัพพลายเออร์ตัวอย่าง จำกัด',
    counterpartyAddress: '88/8 ถนนตัวอย่าง กรุงเทพมหานคร 10200',
    meta: [['วันที่สั่งซื้อ', '19 สิงหาคม 2569'], ['กำหนดส่ง', '26 สิงหาคม 2569']],
    items: a4Items,
    totals: baseTotals,
    signatures: ['ผู้สั่งซื้อ', 'ผู้ขาย'],
  },
  COMBINED_BILLING: {
    rendererFamily: 'A4',
    category: 'CONSOLIDATED',
    title: 'เอกสารรวมบิล',
    englishTitle: 'COMBINED BILLING',
    documentNo: 'CB-2026-0001',
    counterpartyLabel: 'ลูกค้า',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่เอกสาร', '19 สิงหาคม 2569'], ['จำนวนเอกสารรวม', '2 ฉบับ']],
    items: [
      { description: 'ใบส่งของ DN-2026-0001', quantity: '1', unit: 'ฉบับ', price: '5,350.00', amount: '5,350.00' },
      { description: 'ใบส่งของ DN-2026-0002', quantity: '1', unit: 'ฉบับ', price: '5,350.00', amount: '5,350.00' },
    ],
    totals: [['ยอดรวมเอกสาร', '10,700.00']],
    signatures: ['ผู้จัดทำ', 'ผู้รับเอกสาร'],
  },
  FULL_TAX_INVOICE: {
    rendererFamily: 'A4',
    category: 'STATUTORY',
    title: 'ใบกำกับภาษีเต็มรูป',
    englishTitle: 'TAX INVOICE',
    documentNo: 'TAX-2026-0001',
    counterpartyLabel: 'ผู้ซื้อ',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่เอกสาร', '19 สิงหาคม 2569'], ['สาขา', 'สำนักงานใหญ่']],
    items: taxItems,
    totals: baseTotals,
    signatures: ['ผู้รับสินค้า / บริการ', 'ผู้มีอำนาจลงนาม'],
    lockedAuthority: true,
  },
  CREDIT_NOTE: {
    rendererFamily: 'A4',
    category: 'STATUTORY',
    title: 'ใบลดหนี้',
    englishTitle: 'CREDIT NOTE',
    documentNo: 'CN-2026-0001',
    counterpartyLabel: 'ผู้ซื้อ',
    counterpartyName: 'บริษัท ลูกค้าตัวอย่าง จำกัด',
    counterpartyAddress: '99/9 ถนนสุขุมวิท กรุงเทพมหานคร 10110',
    meta: [['วันที่เอกสาร', '19 สิงหาคม 2569'], ['อ้างอิงใบกำกับภาษี', 'TAX-2026-0001']],
    items: [{ description: 'ปรับลดมูลค่าสินค้า / บริการ', quantity: '1', unit: 'รายการ', price: '1,000.00', amount: '1,000.00' }],
    totals: [['มูลค่าลดหนี้', '1,000.00'], ['VAT 7%', '70.00'], ['รวมลดหนี้', '1,070.00']],
    signatures: ['ผู้รับเอกสาร', 'ผู้มีอำนาจลงนาม'],
    lockedAuthority: true,
  },
  SHORT_TAX_INVOICE: {
    rendererFamily: 'THERMAL',
    category: 'STATUTORY',
    title: 'ใบกำกับภาษีอย่างย่อ',
    englishTitle: 'ABB. TAX INVOICE',
    documentNo: 'ST-2026-0001',
    counterpartyLabel: 'ลูกค้า',
    counterpartyName: 'ลูกค้าทั่วไป',
    counterpartyAddress: '',
    meta: [['วันที่', '19/08/2569'], ['เครื่อง', 'POS-01']],
    items: [
      { description: 'สินค้าตัวอย่าง A', quantity: '2', unit: 'ชิ้น', price: '100.00', amount: '200.00' },
      { description: 'สินค้าตัวอย่าง B', quantity: '1', unit: 'ชิ้น', price: '50.00', amount: '50.00' },
    ],
    totals: [['รวมก่อนภาษี', '233.64'], ['VAT 7%', '16.36'], ['ยอดสุทธิ', '250.00']],
    signatures: [],
    lockedAuthority: true,
  },
})

const DEFAULT_PREVIEW_FIXTURE = DOCUMENT_PREVIEW_FIXTURES.QUOTATION

const getDocumentPreviewFixture = (documentPurpose) => {
  const canonical = toCanonicalDocumentCode(documentPurpose)
  return DOCUMENT_PREVIEW_FIXTURES[canonical] || DEFAULT_PREVIEW_FIXTURE
}

export {
  DEFAULT_PREVIEW_FIXTURE,
  DOCUMENT_PREVIEW_FIXTURES,
  getDocumentPreviewFixture,
}
