export const SALES_STORE_RESPONSIBILITY_AUDIT_CONTRACT = Object.freeze({
  runtimeEntrypoint: 'src/features/sales/store/salesStore.js',
  responsibilityClasses: Object.freeze({
    CREATE_SESSION: Object.freeze([
      'saleItems',
      'customerId',
      'paymentList',
      'cardRef',
      'billDiscount',
      'sharedBillDiscountPerItem',
      'saleCompleted',
      'completionState',
      'completionCommandId',
      'setPaymentAmount',
      'setBillDiscount',
      'addSaleItemAction',
      'removeSaleItemAction',
      'clearSaleItemsAction',
      'updateItemDiscountAction',
      'updateSaleItemAction',
      'confirmSaleOrderAction',
      'resetSaleOrderAction',
    ]),
    HISTORY_QUERY: Object.freeze([
      'sales',
      'currentSale',
      'fetchSalesAction',
      'fetchSaleByIdAction',
      'updateSaleDocumentLinesAction',
    ]),
    PRINTABLE_QUERY: Object.freeze([
      'printableSales',
      'searchPrintableSalesAction',
      'normalizePrintableRows',
      'normalizeSaleDetail',
    ]),
    RETURN_AND_COLLECTION: Object.freeze([
      'returnSaleAction',
      'markSalePaidAction',
    ]),
    DASHBOARD_OVERVIEW: Object.freeze([
      'salesOverviewLoading',
      'salesOverviewError',
      'salesOverviewLastLoadedAt',
      'clearSalesOverviewErrorAction',
      'fetchSalesDashboardOverviewAction',
    ]),
    ONLINE_ORDER_CONVERSION: Object.freeze([
      'convertOrderOnlineToSaleAction',
    ]),
    COMPATIBILITY: Object.freeze([
      'normalizeStockItemId',
      'devError',
      'setPaymentAmountAction',
      'setBillDiscountAction',
      'setSharedBillDiscountPerItemAction',
      'setCardRefAction',
      'setLastCreatedSaleIdAction',
      'clearSaleCompletionIdentity',
    ]),
  }),
  safetyRules: Object.freeze({
    destructiveMigrationAllowed: false,
    legacyDeletionAllowed: false,
    runtimeEvidenceRequiredForRemoval: true,
    compatibilitySurfaceMustRemainAvailable: true,
  }),
  targetOwners: Object.freeze({
    CREATE_SESSION: 'src/features/sales/create/store/saleCreateSessionStore.js',
    HISTORY_QUERY: 'src/features/sales/history/store/saleHistoryStore.js',
    PRINTABLE_QUERY: 'src/features/sales/printable/store/printableSaleStore.js',
    RETURN_AND_COLLECTION: 'src/features/sales/returns/store/saleReturnStore.js',
    DASHBOARD_OVERVIEW: 'src/features/sales/dashboard/store/salesDashboardStore.js',
    ONLINE_ORDER_CONVERSION: 'src/features/orderOnline/conversion',
    COMPATIBILITY: 'src/features/sales/shared/compatibility/legacySalesStoreAdapter.js',
  }),
});
