import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

describe('position-first employee authority UI contract', () => {
  it('makes position the capability configuration surface without removing compatibility yet', () => {
    const form = read('src/features/position/components/PositionForm.jsx');
    const catalog = read('src/features/position/components/positionCapabilityCatalog.js');
    const taxPeriodGroup = read('src/features/position/components/taxPeriodCapabilityGroup.js');
    const taxClosingHandoffGroup = read('src/features/position/components/taxClosingHandoffCapabilityGroup.js');
    const accountingOfficeGroup = read('src/features/position/components/accountingOfficeCapabilityGroup.js');
    const createWorkspace = read('src/features/position/workspace/CreatePositionWorkspace.jsx');
    const editWorkspace = read('src/features/position/workspace/EditPositionWorkspace.jsx');

    expect(catalog).toContain("const EMPLOYEE_MANAGE_CAPABILITY = 'employee.manage'");
    expect(catalog).toContain("WORKFLOW: 'repair.workflow'");
    expect(catalog).toContain("PARTS: 'repair.parts'");
    expect(catalog).toContain("HANDOVER: 'repair.handover'");
    expect(catalog).toContain("CUSTOMER_OVERRIDE: 'repair.customer-override'");
    expect(catalog).toContain("ADJUST: 'inventory.adjust'");
    expect(catalog).toContain("TRANSFER: 'inventory.transfer'");
    expect(catalog).toContain("AUDIT: 'inventory.audit'");
    expect(catalog).toContain("AUDIT_FINALIZE: 'inventory.audit.finalize'");
    expect(catalog).toContain("RECEIVE: 'inventory.receive'");
    expect(catalog).toContain("LIFECYCLE: 'inventory.lifecycle'");
    expect(catalog).toContain("QUICK_STOCK: 'inventory.quick-stock'");
    expect(catalog).toContain("QUICK_RECEIPT: 'inventory.quick-receipt'");
    expect(catalog).toContain("QUICK_RECEIPT_FINALIZE: 'inventory.quick-receipt.finalize'");
    expect(catalog).toContain("CORE: 'sales.core'");
    expect(catalog).toContain("COMPLETE: 'sales.complete'");
    expect(catalog).toContain("RETURN: 'sales.return'");
    expect(catalog).toContain("RETURN_DEDUCTION_APPROVE: 'sales.return.deduction-approve'");
    expect(catalog).toContain("PAYMENT_READ: 'sales.payment.read'");
    expect(catalog).toContain("PAYMENT_MANAGE: 'sales.payment.manage'");
    expect(catalog).toContain("PAYMENT_CANCEL: 'sales.payment.cancel'");
    expect(catalog).toContain("SETTLEMENT_CLOSE: 'sales.settlement.close'");
    expect(catalog).toContain("DOCUMENT_PREPARE: 'sales.document.prepare'");
    expect(catalog).toContain("DOCUMENT_LOCK: 'sales.document.lock'");
    expect(catalog).toContain("DOCUMENT_REPLACE: 'sales.document.replace'");
    expect(catalog).toContain("DOCUMENT_TAX_PUBLISH: 'sales.document.tax-publish'");
    expect(catalog).toContain("READ: 'tax.output.read'");
    expect(catalog).toContain("PREPARE: 'tax.output.prepare'");
    expect(catalog).toContain("ISSUE: 'tax.output.issue'");
    expect(catalog).toContain("CREDIT_NOTE: 'tax.output.credit-note'");
    expect(catalog).toContain("LIFECYCLE: 'tax.output.lifecycle'");
    expect(catalog).toContain("FILING_READ: 'tax.output.filing.read'");
    expect(catalog).toContain("FILING_PREPARE: 'tax.output.filing.prepare'");
    expect(catalog).toContain("FILING_SUBMIT: 'tax.output.filing.submit'");
    expect(catalog).toContain("READ: 'tax.input.read'");
    expect(catalog).toContain("REVIEW: 'tax.input.review'");
    expect(catalog).toContain("FILING: 'tax.input.filing'");
    expect(catalog).toContain("AUDIT: 'tax.input.audit'");
    expect(catalog).toContain("PERIOD_CONTROL: 'tax.input.period-control'");
    expect(catalog).toContain("PURCHASE_ORDER: 'procurement.purchase-order'");
    expect(catalog).toContain("PURCHASE_ORDER_CONTROL: 'procurement.purchase-order.control'");
    expect(catalog).toContain("SUPPLIER: 'procurement.supplier'");
    expect(catalog).toContain("SUPPLIER_DELETE: 'procurement.supplier.delete'");
    expect(catalog).toContain("SUPPLIER_PAYMENT_READ: 'procurement.supplier-payment.read'");
    expect(catalog).toContain("SUPPLIER_PAYMENT_MANAGE: 'procurement.supplier-payment.manage'");
    expect(catalog).toContain("SUPPLIER_PAYMENT_VOID: 'procurement.supplier-payment.void'");
    expect(catalog).toContain("RECEIPT: 'procurement.receipt'");
    expect(catalog).toContain("RECEIPT_FINALIZE: 'procurement.receipt.finalize'");
    expect(catalog).toContain('งานซ่อมและเคลม');
    expect(catalog).toContain('ดำเนินขั้นตอนงานซ่อม');
    expect(catalog).toContain('จัดการอะไหล่ในงานซ่อม');
    expect(catalog).toContain('ส่งมอบงานซ่อม');
    expect(catalog).toContain('อนุญาตรับงานกรณีเจ้าของอุปกรณ์ไม่ตรง');
    expect(catalog).toContain('สต๊อกและการเคลื่อนไหวสินค้า');
    expect(catalog).toContain('ปรับยอดสต๊อก');
    expect(catalog).toContain('โอนสต๊อกระหว่างสาขา');
    expect(catalog).toContain('ตรวจนับสต๊อก');
    expect(catalog).toContain('ยืนยันหรือยกเลิกรอบตรวจนับ');
    expect(catalog).toContain('รับสินค้าเข้าสต๊อก');
    expect(catalog).toContain('จัดการสถานะรายการสต๊อก');
    expect(catalog).toContain('เพิ่มสต๊อกด่วน');
    expect(catalog).toContain('จัดทำใบรับสินค้าด่วน');
    expect(catalog).toContain('ยืนยันหรือยกเลิกใบรับสินค้าด่วน');
    expect(catalog).toContain('การขายและหน้าขายสินค้า');
    expect(catalog).toContain('ใช้งานการขาย');
    expect(catalog).toContain('ยืนยันการขาย');
    expect(catalog).toContain('รับคืนสินค้า');
    expect(catalog).toContain('อนุมัติการหักยอดคืน');
    expect(catalog).toContain('ดูข้อมูลการชำระเงิน');
    expect(catalog).toContain('บันทึกการชำระเงิน');
    expect(catalog).toContain('ยกเลิกรายการชำระเงิน');
    expect(catalog).toContain('ปิดยอดการขาย');
    expect(catalog).toContain('จัดเตรียมเอกสารการขาย');
    expect(catalog).toContain('ล็อกเอกสารการขาย');
    expect(catalog).toContain('จัดทำเอกสารทดแทน');
    expect(catalog).toContain('เผยแพร่เอกสารเข้าสู่ภาษี');
    expect(catalog).toContain('ภาษีขายและเอกสารภาษี');
    expect(catalog).toContain('ดูข้อมูลภาษีขาย');
    expect(catalog).toContain('เตรียมเอกสารภาษีขาย');
    expect(catalog).toContain('ออกเอกสารภาษีขาย');
    expect(catalog).toContain('ออกใบลดหนี้ภาษีขาย');
    expect(catalog).toContain('ควบคุมสถานะเอกสารภาษี');
    expect(catalog).toContain('ดูชุดยื่นภาษีขาย');
    expect(catalog).toContain('เตรียมชุดยื่นภาษีขาย');
    expect(catalog).toContain('ยืนยันการยื่นภาษีขาย');
    expect(catalog).toContain('ภาษีซื้อและการยื่นภาษี');
    expect(catalog).toContain('ดูข้อมูลภาษีซื้อ');
    expect(catalog).toContain('ตรวจสอบและตัดสินใจภาษีซื้อ');
    expect(catalog).toContain('จัดชุดและยื่นภาษีซื้อ');
    expect(catalog).toContain('จัดทำชุดตรวจสอบภาษีซื้อ');
    expect(catalog).toContain('ควบคุมงวดภาษีซื้อ');
    expect(catalog).toContain('จัดซื้อและใบรับสินค้า');
    expect(catalog).toContain('จัดการข้อมูล Supplier');
    expect(catalog).toContain('ลบข้อมูล Supplier');
    expect(catalog).toContain('จัดทำใบสั่งซื้อ');
    expect(catalog).toContain('ควบคุมสถานะหรือลบใบสั่งซื้อ');
    expect(catalog).toContain('ดูข้อมูลการชำระ Supplier');
    expect(catalog).toContain('จัดการการชำระ Supplier');
    expect(catalog).toContain('ยกเลิกรายการชำระ Supplier');
    expect(catalog).toContain('จัดทำใบรับสินค้าจาก PO');
    expect(catalog).toContain('ยืนยันหรือลบใบรับสินค้า');

    expect(taxPeriodGroup).toContain("READ: 'tax.period.read'");
    expect(taxPeriodGroup).toContain("MANAGE: 'tax.period.manage'");
    expect(taxPeriodGroup).toContain("REOPEN: 'tax.period.reopen'");
    expect(taxPeriodGroup).toContain('งวดภาษีและการปิดงวด');
    expect(taxPeriodGroup).toContain('ดูข้อมูลงวดภาษี');
    expect(taxPeriodGroup).toContain('จัดการและปิดงวดภาษี');
    expect(taxPeriodGroup).toContain('เปิดงวดภาษีอีกครั้ง');

    expect(taxClosingHandoffGroup).toContain("READ: 'tax.closing-handoff.read'");
    expect(taxClosingHandoffGroup).toContain("FINALIZE: 'tax.closing-handoff.finalize'");
    expect(taxClosingHandoffGroup).toContain('ส่งมอบงานปิดภาษี');
    expect(taxClosingHandoffGroup).toContain('ดูชุดส่งมอบงานปิดภาษี');
    expect(taxClosingHandoffGroup).toContain('ยืนยันชุดส่งมอบงานปิดภาษี');

    expect(accountingOfficeGroup).toContain("READ: 'tax.accounting-office.read'");
    expect(accountingOfficeGroup).toContain('ชุดข้อมูลสำหรับสำนักงานบัญชี');
    expect(accountingOfficeGroup).toContain('ดูชุดข้อมูลสำหรับสำนักงานบัญชี');

    expect(form).toContain("import { CAPABILITY_GROUPS } from './positionCapabilityCatalog'");
    expect(form).toContain("import { TAX_PERIOD_CAPABILITY_GROUP } from './taxPeriodCapabilityGroup'");
    expect(form).toContain("import { TAX_CLOSING_HANDOFF_CAPABILITY_GROUP } from './taxClosingHandoffCapabilityGroup'");
    expect(form).toContain("import { ACCOUNTING_OFFICE_CAPABILITY_GROUP } from './accountingOfficeCapabilityGroup'");
    expect(form).toContain('POSITION_CAPABILITY_GROUPS.map');
    expect(form).toContain('สิทธิ์ของตำแหน่งงาน');
    expect(form).toContain('เริ่มใช้สิทธิ์จากตำแหน่งนี้');
    expect(form).toContain('v2Role จะคงไว้เป็นชั้นรองรับของระบบเดิมระหว่างการย้าย');
    expect(form).toContain('payload.capabilities = capabilities');

    expect(createWorkspace).toContain("capabilities: Array.isArray(payload?.capabilities) ? payload.capabilities : []");
    expect(createWorkspace).toContain("initialValues={{ name: '', description: '', capabilities: [] }}");

    expect(editWorkspace).toContain('if (Array.isArray(payload?.capabilities))');
    expect(editWorkspace).toContain('capabilities: Array.isArray(current?.capabilities) ? current.capabilities : null');
  });
});
