import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(filename), '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');
const includes = (source, value, message) => {
  if (!source.includes(value)) throw new Error(message || `Expected source to include: ${value}`);
};
const excludes = (source, value, message) => {
  if (source.includes(value)) throw new Error(message || `Expected source to exclude: ${value}`);
};

const api = read('src/features/quotation/api/quotationApi.js');
const createPage = read('src/features/quotation/pages/CreateQuotationPage.jsx');
const editor = read('src/features/quotation/pages/QuotationEditorPage.jsx');
const printPage = read('src/features/quotation/pages/QuotationPrintPage.jsx');
const routes = read('src/routes/partner/salesRoutes.jsx');
const sidebar = read('src/config/sidebarSalesItems.js');

includes(api, "apiClient.post('/sales/quotations', { customerId })", 'Quotation draft creation endpoint is required');
includes(api, 'addQuotationLine', 'Quotation API must expose direct line creation authority');
includes(api, 'updateQuotationLine', 'Quotation API must expose line mutation authority for document workspace editing');
includes(createPage, 'data-testid="quotation-create-empty-draft"', 'Zero-item draft creation must stay an explicit tested action');
includes(createPage, "customerId: selectedCustomer?.id || null", 'Customer lookup must remain optional');
includes(createPage, 'เริ่มจากเอกสารเปล่าได้', 'Create surface must explain document-first workflow');
excludes(createPage, 'items.length', 'Create action must never depend on quotation item count');
excludes(createPage, 'productId', 'Create surface must not require or own product selection');

includes(editor, 'searchStoreCustomersAction', 'Quotation intake must provide canonical store-scoped customer search');
includes(editor, 'chooseCustomer', 'Quotation intake must allow selecting or changing the quotation customer');
includes(editor, 'buildPreservedDraftPayload', 'Customer selection must preserve existing draft document fields while changing customer authority');
includes(editor, 'searchSaleItems', 'Quotation intake must keep product catalog discovery as an optional helper');
includes(editor, 'groupProductSearchResults', 'Quotation intake must preserve per-product stock context from sales search results');
includes(editor, 'availableQuantity', 'Quotation product helper must surface useful current stock availability context');
includes(editor, 'Barcode/SN:', 'Quotation product helper must surface stock identifiers when present');
includes(editor, 'ข้อมูลสต๊อกเป็นข้อมูลประกอบการเสนอราคา ไม่ใช่การจองสต๊อก', 'Quotation intake must never imply that stock visibility creates a reservation');
includes(editor, 'data-testid="quotation-intake-overview"', 'Quotation intake must show a useful overview of current quotation lines');
includes(editor, 'สินค้าในระบบ', 'Quotation intake overview must distinguish product-assisted lines from manual lines');
includes(editor, 'addProductHelper', 'Product helper selection must create a starter quotation line');
includes(editor, 'addQuotationLine(quotationId', 'Product-assisted starter lines must persist through canonical quotation line authority');
includes(editor, 'เป็นตัวช่วยเท่านั้น — เพิ่มแล้วสามารถแก้รายละเอียดทั้งหมดต่อบนหน้าเอกสาร', 'Product helper must remain subordinate to the document workspace');
includes(editor, 'Manual ได้จากหน้าเอกสารโดยตรง', 'Manual-first authoring must remain explicit after simplifying intake');
includes(editor, 'ไปหน้าเอกสาร', 'Quotation intake must keep a single document-workspace action at the bottom of the flow');
excludes(editor, 'หน้านี้ใช้สำหรับเลือกลูกค้าและสินค้าเท่านั้น', 'Redundant quotation intake header copy must not return');
excludes(editor, 'เปิดหน้าเอกสาร', 'Duplicate top document action must not return');
includes(editor, 'updateQuotationLine(quotationId, line.id', 'Intake quantity and price adjustments must persist through canonical quotation line authority');
includes(editor, 'saveLineQuickEdit', 'Quotation intake must expose a dedicated quick edit path instead of reusing the document line editor');
includes(editor, 'data-testid={`quotation-intake-quantity-${line.id}`}', 'Quotation intake must allow draft quantity adjustment per line');
includes(editor, 'min="1" step="1"', 'Quotation intake quantity control must use whole-number increments');
includes(editor, 'Number.isInteger(quantity)', 'Quotation intake must reject fractional quantity even when typed manually');
includes(editor, 'จำนวนต้องเป็นจำนวนเต็มตั้งแต่ 1 ขึ้นไป', 'Quotation intake must explain whole-number quantity validation');
includes(editor, 'data-testid={`quotation-intake-adjustment-${line.id}`}', 'Quotation intake must allow relative price adjustment per line');
includes(editor, 'ปรับราคา (+/-)', 'Quotation intake quick editing should mirror the sales-page price-adjustment mental model');
includes(editor, 'ราคาหลังปรับ', 'Quotation intake must preview the adjusted price before save');
includes(editor, 'data-testid="quotation-intake-totals"', 'Quotation intake must expose a useful commercial totals panel');
includes(editor, 'const adjustedTotal = quotationItems.reduce((sum, line) => {', 'Quotation totals must derive from live per-line draft values');
includes(editor, 'return sum + (quantity * adjustedPrice);', 'Quotation totals must update immediately from draft quantity and adjusted price before save');
includes(editor, 'ยอดรวมราคาหลังปรับ', 'Quotation intake totals must use the adjusted quotation price as the sole commercial price');
includes(editor, 'มูลค่าก่อนภาษี', 'Quotation intake totals must expose pre-tax value');
includes(editor, 'ยอดสุทธิประมาณการ', 'Quotation intake must show an approximate grand total before entering the document workspace');
includes(editor, 'ไม่ตัดหรือจองสต๊อกสินค้า', 'Commercial quick editing must remain independent of stock reservation authority');
excludes(editor, 'ส่วนลดรายการ', 'Quotation intake must not expose line-discount semantics');
excludes(editor, 'ส่วนลดท้ายบิล', 'Quotation intake must not expose bill-discount semantics');
excludes(editor, 'เนื้อหาเอกสาร', 'Quotation intake must not own document subject/introduction authoring');
excludes(editor, 'ข้อความท้ายเอกสาร', 'Quotation intake must not own closing-note authoring');
excludes(editor, 'เงื่อนไขเอกสาร', 'Quotation intake must not own document terms controls');
excludes(editor, 'handleSaveLine', 'Quotation intake must not retain the old manual line editor');
excludes(editor, 'issueQuotation', 'Quotation lifecycle issue action must not remain mixed into customer/product intake');

includes(printPage, "documentType: 'QUOTATION'", 'Quotation print must use store document-header authority');
includes(printPage, 'whitespace-pre-wrap', 'A4 document must preserve multiline descriptions');
includes(printPage, 'tableFillerHeightMm', 'Quotation table must reserve formal document body space instead of collapsing around short content');
includes(printPage, '130 - occupied', 'Quotation table must extend roughly two additional row heights toward the lower document reserve');
includes(printPage, 'quotation-table-filler', 'Reserved table body must retain the document column grid');
includes(printPage, 'quotation-document-header', 'Quotation must expose a dedicated document header boundary');
includes(printPage, 'deliveryAlignedLogoSize', 'Quotation header must keep delivery-note-aligned logo bounds');
includes(printPage, 'min-h-[31mm]', 'Quotation header must preserve a stable delivery-note-like identity band');
includes(printPage, 'quotation-document-title', 'Quotation title must be a centered document anchor like the delivery note standard');
includes(printPage, 'ต้นฉบับลูกค้า', 'Issued quotation must expose a customer-original document marker');
includes(printPage, 'quotation-info-panel', 'Customer and document metadata must use consistent information panels');
includes(printPage, '<span className="font-semibold">เลขที่:</span>', 'Quotation number must live inside document metadata rather than compete with the document title');
includes(printPage, 'quotation-settlement grid min-h-[19mm]', 'Terms and totals must form a compact delivery-note-like footer row attached to the item table');
includes(printPage, 'border-b border-slate-400 px-2.5 py-1', 'Quotation totals must use compact ruled summary rows like the delivery note standard');
includes(printPage, 'quotation-signatures absolute bottom-[5mm]', 'Quotation signatures must stay anchored near the physical page bottom');
includes(printPage, 'body .quotation-signatures { position: absolute !important;', 'Print CSS must preserve the anchored quotation signature baseline');
excludes(printPage, 'quotation-settlement grid h-[34mm]', 'Oversized lower settlement block must not return');
excludes(printPage, 'quotation-signatures mt-auto', 'Quotation signatures must not be forced by flex auto spacing');
includes(printPage, 'editingLineId', 'Quotation A4 workspace must track the document line being edited');
includes(printPage, 'beginLineEdit', 'Quotation A4 workspace must expose direct per-line editing');
includes(printPage, 'beginNewLine', 'Quotation A4 workspace must expose direct line creation');
includes(printPage, "editingLineId === 'NEW'", 'New-line authoring must have an explicit document workspace state');
includes(printPage, 'addQuotationLine(quotationId, payload)', 'New document lines must persist through canonical quotation line authority');
includes(printPage, 'quotation-add-line-row print:hidden', 'Draft A4 workspace must place the add action as the next document row');
includes(printPage, 'aria-label="เพิ่มรายการถัดไปบนใบเสนอราคา"', 'Next-row add action must be explicit and accessible');
excludes(printPage, '> เพิ่มรายการ</button>', 'Add-line authority must not fall back to a detached button below the table');
includes(printPage, 'quotation-line-editor print:hidden', 'Inline line editor must remain screen-only and never print');
includes(printPage, 'updateQuotationLine(quotationId, editingLineId, payload)', 'Inline document editing must persist through canonical quotation line authority');
includes(printPage, 'พิมพ์เองได้ทั้งหมด ไม่จำเป็นต้องอ้างอิงสินค้า', 'Direct line creation must preserve manual-first quotation semantics');
includes(printPage, 'รายละเอียดเพิ่มเติม', 'Inline editor must support multiline document details');
includes(printPage, 'ราคา/หน่วย', 'Inline editor must support the offered unit price');
includes(printPage, 'min="1" step="1"', 'Document workspace quantity control must use whole-number increments');
includes(printPage, 'Number.isInteger(quantity)', 'Document workspace must reject fractional quantity even when typed manually');
includes(printPage, 'ยอดราคาหลังปรับ', 'Quotation print totals must use the adjusted offered price directly');
excludes(printPage, '<span className="mb-1 block font-semibold text-slate-700">ส่วนลด</span>', 'Document workspace must not expose a discount input');
excludes(printPage, 'ส่วนลดรายการ', 'Printed quotation must not expose line discounts');
excludes(printPage, 'ส่วนลดท้ายบิล', 'Printed quotation must not expose bill discounts');
includes(printPage, 'print:w-[45%]', 'Printable table must reclaim the screen-only action column width');
includes(printPage, 'aria-label="แก้ไขรายการนี้บนใบเสนอราคา"', 'Each draft quotation row must expose an accessible edit action');
includes(printPage, 'ผู้เสนอราคา / QUOTED BY', 'Quotation signature language must be explicit and bilingual');
includes(printPage, 'ผู้ตอบรับใบเสนอราคา / ACCEPTED BY', 'Customer acceptance signature must remain explicit');
includes(printPage, 'width: 195mm !important', 'Quotation print must follow the established 195mm printable A4 frame');
includes(printPage, 'height: 280mm !important', 'Quotation print must follow the established 280mm printable A4 height');
includes(printPage, 'overflow: hidden !important', 'Single-page quotation shell must prevent phantom overflow pages');
excludes(printPage, 'ไม่มีรายการสินค้า —', 'Formal quotation print must not expose application-style empty-state copy');

includes(routes, "{ path: 'quotations', element: <QuotationListPage /> }", 'Quotation list route is required');
includes(routes, "{ path: 'quotations/new', element: <CreateQuotationPage /> }", 'Quotation create route is required');
includes(routes, "{ path: 'quotations/:quotationId', element: <QuotationEditorPage /> }", 'Quotation intake route is required');
includes(routes, "{ path: 'quotations/:quotationId/print', element: <QuotationPrintPage /> }", 'Quotation A4 print route is required');
includes(sidebar, "label: 'ใบเสนอราคา'", 'Sales navigation must expose quotation workspace');

console.log('Quotation Document-First E2E Client contract: PASS');