export const SALE_RETURN_ITEM_KIND = Object.freeze({
  SERIALIZED: 'SERIALIZED',
  SIMPLE: 'SIMPLE',
});

export const SALE_RETURN_REFUND_METHOD = Object.freeze({
  CASH: 'CASH',
  TRANSFER: 'TRANSFER',
  CARD: 'CARD',
  STORE_CREDIT: 'STORE_CREDIT',
  OTHER: 'OTHER',
});

export const SALE_RETURN_FAILURE_CODE = Object.freeze({
  COMPLETION_CONFLICT: 'RETURN_COMPLETION_CONFLICT',
  STOCK_CONFLICT: 'RETURN_STOCK_CONFLICT',
  QUANTITY_CONFLICT: 'RETURN_QUANTITY_CONFLICT',
  REFUND_EXCEEDS_ELIGIBLE: 'REFUND_EXCEEDS_ELIGIBLE',
  REFUND_EVIDENCE_MISMATCH: 'REFUND_EVIDENCE_MISMATCH',
  DEDUCTION_REASON_REQUIRED: 'DEDUCTION_REASON_REQUIRED',
  DEDUCTION_APPROVAL_REQUIRED: 'DEDUCTED_REFUND_APPROVAL_REQUIRED',
  INVALID_SOURCE_PAYMENT: 'INVALID_SOURCE_PAYMENT',
});

export const SALE_RETURN_ROUTE = Object.freeze({
  SEARCH: 'sale-return',
  CREATE: 'sale-return/create/:saleId',
});
