const round2 = (n) => Math.round((Number(n) || 0) * 100) / 100
const n = (v) => { const x = Number(v); return Number.isFinite(x) ? x : 0 }
const getUnitPrice = (item) => { if (!item) return 0; for (const v of [item.unitPriceIncVat, item.unitPrice, item.lineUnitPrice]) { const num = n(v); if (num > 0) return num } const qty = n(item?.quantity); const amount = n(item?.amount ?? item?.total ?? item?.totalAmount); return qty > 0 && amount > 0 ? round2(amount / qty) : 0 }
const getLineTotalSatang = (item) => { const amount = n(item?.amount ?? item?.total ?? item?.totalAmount); if (amount > 0) return Math.round(amount * 100); const qty = n(item?.quantity) || 1; return Math.round(getUnitPrice(item) * 100) * qty }
const normalizeGroupText = (value) => String(value ?? '').trim().replace(/\s+/g, ' ')
const getGroupProductId = (item) => item?.productId ?? item?.product?.id ?? item?.stockItem?.productId ?? item?.simpleItem?.productId ?? null
const getGroupUnitKey = (item) => Math.round(getUnitPrice(item) * 100)
const getFirstTextValue = (...values) => { for (const value of values) { const text = normalizeGroupText(value); if (text) return text } return '' }
const getSerialIdentity = (item) => getFirstTextValue(item?.serialNo, item?.serialNumber, item?.serial, item?.sn, item?.imei, item?.imei1, item?.imei2, item?.stockItem?.serialNo, item?.stockItem?.serialNumber, item?.stockItem?.serial, item?.stockItem?.sn, item?.stockItem?.imei, item?.stockItem?.imei1, item?.stockItem?.imei2, item?.simpleItem?.serialNo, item?.simpleItem?.serialNumber, item?.simpleItem?.serial, item?.simpleItem?.sn, item?.simpleItem?.imei)
const isExplicitSerializedItem = (item) => { const flags = [item?.isSerialized,item?.hasSerial,item?.requireSerial,item?.requiresSerial,item?.trackSerial,item?.trackingSerial,item?.product?.isSerialized,item?.product?.hasSerial,item?.product?.requireSerial,item?.product?.requiresSerial,item?.product?.trackSerial,item?.product?.trackingSerial]; if (flags.some((v) => v === true)) return true; const codeType = normalizeGroupText(item?.codeType || item?.product?.codeType).toUpperCase(); return ['S','SN','SERIAL','IMEI'].includes(codeType) }
const canMergeReceiptItem = (item) => !getSerialIdentity(item) && !isExplicitSerializedItem(item)
const getReceiptGroupKey = (item, index = 0) => { const productId = getGroupProductId(item); const description = normalizeGroupText(item?.documentDescription || item?.productName || item?.documentDescriptionRaw); const prefix = normalizeGroupText(item?.documentPrefix); const suffix = normalizeGroupText(item?.documentSuffix); const baseKey = [productId || description || item?.id || 'unknown', getGroupUnitKey(item), prefix, description, suffix].join('|'); if (canMergeReceiptItem(item)) return baseKey; return `${baseKey}|serial:${getSerialIdentity(item) || item?.id || index}` }
const appendUnique = (base = [], values = []) => Array.from(new Set([...base.filter((v) => v != null), ...values.filter((v) => v != null)]))
const getItemOwnIdList = (item) => Array.isArray(item?.saleItemIds) && item.saleItemIds.length ? item.saleItemIds : (item?.id != null ? [item.id] : [])
const getItemSimpleIdList = (item) => Array.isArray(item?.simpleItemIds) && item.simpleItemIds.length ? item.simpleItemIds : [item?.simpleItemId,item?.stockItemId,item?.serialItemId,item?.stockItem?.id,item?.simpleItem?.id].filter((v) => v != null)
export const buildReceiptItems = (items = []) => { if (!Array.isArray(items)) return []; const map = new Map(); items.forEach((item, index) => { if (!item) return; const key = getReceiptGroupKey(item, index); const qty = n(item?.quantity) || 1; const lineTotalSatang = getLineTotalSatang(item); const saleItemIds = getItemOwnIdList(item); const simpleItemIds = getItemSimpleIdList(item); if (!map.has(key)) { map.set(key,{...item,id:item?.id ?? `receipt-line-${index}`,documentLineKey:key,quantity:qty,amount:lineTotalSatang/100,total:lineTotalSatang/100,totalAmount:lineTotalSatang/100,saleItemIds,simpleItemIds,hasDocumentLine:Boolean(item?.hasDocumentLine || item?.documentPrefix || item?.documentSuffix)}); return } const current = map.get(key); const nextTotalSatang = Math.round(n(current?.amount ?? current?.total ?? current?.totalAmount) * 100) + lineTotalSatang; map.set(key,{...current,quantity:n(current.quantity)+qty,amount:nextTotalSatang/100,total:nextTotalSatang/100,totalAmount:nextTotalSatang/100,saleItemIds:appendUnique(current.saleItemIds,saleItemIds),simpleItemIds:appendUnique(current.simpleItemIds,simpleItemIds),hasDocumentLine:Boolean(current?.hasDocumentLine || item?.hasDocumentLine || item?.documentPrefix || item?.documentSuffix)}) }); return Array.from(map.values()) }
export default buildReceiptItems
