export const projectCreateSaleWorkflow = ({
  cart,
  itemSearch,
  completion,
  documentHandoff,
  heldCart,
  customer,
  presentation,
}) => ({
  customer,
  presentation,
  cart: {
    items: cart.items,
    itemKeySet: cart.itemKeySet,
    add: cart.add,
    remove: cart.remove,
    update: cart.update,
    setSimpleQuantity: cart.setSimpleQuantity,
    clear: cart.clear,
  },
  itemSearch: {
    error: itemSearch.error,
    setError: itemSearch.setError,
    handleBarcodeSearch: itemSearch.handleBarcodeSearch,
    resetInput: itemSearch.resetInput,
    selection: itemSearch.selection,
    closeSelection: itemSearch.closeSelection,
    selectSearchItem: itemSearch.selectSearchItem,
  },
  completion: {
    isSubmitting: completion.isSubmitting,
    setIsSubmitting: completion.setIsSubmitting,
    confirm: completion.confirm,
    recovery: completion.recovery,
  },
  documentHandoff: {
    saleOption: documentHandoff.saleOption,
    setSaleOption: documentHandoff.setSaleOption,
    includeDeliveryNote: documentHandoff.includeDeliveryNote,
    setIncludeDeliveryNote: documentHandoff.setIncludeDeliveryNote,
    handleConfirmed: documentHandoff.handleConfirmed,
  },
  heldCart,
});
